name: w_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.0.0
  jwt_decoder: ^2.0.1
  flutter_feather_icons: ^2.0.0+1
  flutter_rating_bar: ^4.0.1
  http: ^1.1.0
  flutter_svg: ^2.0.7
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
   - .env
   - assets/
   - assets/images/
   - assets/images/icons/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200

        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300

        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400

        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500

        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600

        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
