name: w_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.4

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  email_validator: '^2.1.16'
  equatable: ^2.0.5
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.0.0
  jwt_decoder: ^2.0.1
  flutter_feather_icons: ^2.0.0+1
  flutter_rating_bar: ^4.0.1
  http: ^1.1.0
  flutter_svg: ^2.0.7
  flutter_localizations:
    sdk: flutter
  socket_io_client: ^2.0.3+1
  flutter_keyboard_visibility: ^5.4.1
  image_picker: ^1.0.4
  freezed_annotation: ^0.14.3
  cached_network_image: ^3.3.0
  url_launcher: ^6.2.1
  flutter_markdown: ^0.6.18+2
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.1
  flutter_linkify: ^6.0.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  uni_links: ^0.5.1
  share_plus: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.7


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logos/Whistle.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
   - .env
   - assets/
   - assets/images/
   - assets/images/icons/
   - assets/images/logos/
   - assets/images/ilustrations/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200

        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300

        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400

        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500

        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600

        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
