// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3ymaY6YroM3at7wXGVGYCaZbPVHdVafk',
    appId: '1:71133385658:web:a9e45adc63e08df05d8383',
    messagingSenderId: '71133385658',
    projectId: 'whistleblowwer-notificaciones',
    authDomain: 'whistleblowwer-notificaciones.firebaseapp.com',
    storageBucket: 'whistleblowwer-notificaciones.appspot.com',
    measurementId: 'G-VPCCH6T1XT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg-PDRoVVBUV8ygcDNdybRv02d19Ke-hc',
    appId: '1:71133385658:android:04a8e2120468766f5d8383',
    messagingSenderId: '71133385658',
    projectId: 'whistleblowwer-notificaciones',
    storageBucket: 'whistleblowwer-notificaciones.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsM2nh_VLSM0f853dPJGbtdpqwwDS8tkA',
    appId: '1:71133385658:ios:08b5af148dd0874a5d8383',
    messagingSenderId: '71133385658',
    projectId: 'whistleblowwer-notificaciones',
    storageBucket: 'whistleblowwer-notificaciones.appspot.com',
    iosBundleId: 'com.whistleblowwer.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsM2nh_VLSM0f853dPJGbtdpqwwDS8tkA',
    appId: '1:71133385658:ios:601b7c851005d7b55d8383',
    messagingSenderId: '71133385658',
    projectId: 'whistleblowwer-notificaciones',
    storageBucket: 'whistleblowwer-notificaciones.appspot.com',
    iosBundleId: 'com.example.wApp.RunnerTests',
  );
}
